name: clj-kondo
on:
  push:
      branches:
        - main
  pull_request:
jobs:
  run-clj-kondo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup babashka
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: 0.8.156
      - name: Run clj-kondo linting
        run: bb lint
